name: Composer Update

on:
  schedule:
    - cron: '30 16 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    container: public.ecr.aws/unocha/php-k8s:8.2-stable
    steps:

      - name: Workaround Git Issue
        id: workaround
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Composer Install
        id: install
        run: composer install

      - name: Composer Outdated
        id: outdated
        uses: mathiasvr/command-output@v1
        with:
          run: composer outdated drupal/*
        continue-on-error: true

      - name: Composer Update
        id: update
        uses: mathiasvr/command-output@v1
        with:
          run: composer update --with-dependencies drupal/*
        continue-on-error: true

      - name: Create Pull Request
        id: pull
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: "[UPDATES] Periodic pull request after updating all outdated drupal packages."
          title: "[UPDATES] Periodic Updates"
          body: |
            - Automatic pull request after trying to run composer update drupal/* on all the Drupal packages.
          committer: "Donna Benjamin <me@kattekrab.net>"
          author: "Donna Benjamin <me@kattekrab.net>"
          branch: update/patch
          branch-suffix: short-commit-hash
          base: main
          assignees: kattekrab
          team-reviewers: kattekrab

      - name: Post Comment
        uses: actions/github-script@0.9.0
        env:
          OUTDATED: "composer outdated\n${{ steps.outdated.outputs.stdout }}"
          UPDATES: "composer update\n${{ steps.update.outputs.stdout }}"
          ERRORS: "composer errors\n${{ steps.update.outputs.stderr }}"
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const output = `#### Composer Update \`${{ steps.update.outcome }}\`
            #### Running \`composer update -W drupal/*\` to update all Drupal core and contrib packages
            
            <details><summary>Composer Outdated</summary>
            
            \`\`\`${process.env.OUTDATED}\`\`\`
            
            </details>
            <details><summary>Composer Update Status</summary>

            \`\`\`${process.env.UPDATES}\`\`\`
            
            </details>
            <details><summary>Composer Update Messages</summary>
            
            \`\`\`${process.env.ERRORS}\`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: ${{ steps.pull.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
